QUESTIONS = [
    ("OFP", "nav", "Operational Flight Plan — your full SimBrief flight document",
     ["Outbound Flight Path — the planned departure track",
      "Official Fuel Procedure — refuelling sign-off checklist",
      "Overflight Permit — diplomatic clearance for foreign airspace"]),
    ("VFR", "atc", "Visual Flight Rules — flying by visual reference to the ground",
     ["Verified Flight Record — logged data from the FMC",
      "Variable Frequency Radio — multi-band comms unit",
      "Vertical Fix Reference — a charted altitude constraint"]),
    ("IFR", "atc", "Instrument Flight Rules — flying solely by instruments, no visual reference required",
     ["Initial Fix Report — position call at the first waypoint",
      "In-Flight Radar — weather radar system",
      "Integrated Frequency Range — radio spectrum allocation"]),
    ("FL", "nav", "Flight Level — altitude in hundreds of feet above standard pressure (1013hPa)",
     ["Fixed Limit — maximum permitted speed at a given altitude",
      "Forward Leg — the outbound segment of a route",
      "Fuel Load — total usable fuel quantity on board"]),
    ("TAS", "perf", "True Airspeed — actual speed through the air, corrected for altitude and temperature",
     ["Traffic Advisory System — TCAS display mode",
      "Transponder Activation Signal — SSR interrogation pulse",
      "Terminal Approach Speed — Vref for landing"]),
    ("GS", "perf", "Ground Speed — your speed over the ground after wind is factored in",
     ["Glide Slope — the vertical component of an ILS approach",
      "Gate Signal — ATC pushback approval call",
      "Gust Spread — difference between steady wind and gust speed"]),
    ("QNH", "wx", "Altimeter setting that makes your altimeter read true altitude above sea level",
     ["Qualified Navigation Heading — verified magnetic track",
      "Queue Notification Hold — ground delay programme message",
      "Quadrant Navigation Height — sector safe altitude"]),
    ("CAVOK", "wx", "Ceiling And Visibility OK — visibility 10km+, no significant cloud below 5,000ft, no weather",
     ["Controlled Airspace Vertical Overlay Keep-out zone",
      "Civil Aviation Operator Knowledge assessment",
      "Cruise Altitude Verified OK — dispatcher confirmation"]),
    ("METAR", "wx", "Meteorological Aerodrome Report — current actual weather observation at an airfield",
     ["Mandatory En-route Traffic Advisory Report",
      "Minimum En-route Terrain Altitude Reading",
      "Multi-Engine Training Approval Record"]),
    ("TAF", "wx", "Terminal Aerodrome Forecast — weather forecast for an airfield, typically 24 hours ahead",
     ["Traffic Advisory Frequency — UNICOM or AFIS channel",
      "Transponder Acknowledgement Frame — SSR data packet",
      "Taxiway Allocation Form — apron management document"]),
    ("SIGMET", "wx", "Significant Meteorological Information — warning of serious en-route hazards like TS or icing",
     ["Standard Instrument Go-around Minimum Entry Time",
      "Secondary ILS Guidance Monitoring Equipment",
      "Squawk Identification Ground Met Entry Tag"]),
    ("AIRMET", "wx", "Airmen's Meteorological Information — lower-level weather advisory aimed at light aircraft",
     ["Airspace Management Entry Tag — sector boundary label",
      "Airport Meteorological Equipment Test schedule",
      "Altitude Indicator Reading — Met office instrument"]),
    ("TS", "wx", "Thunderstorm — active convective storm with lightning, a serious flight hazard",
     ["Transition Symbol — procedure turn marker on a chart",
      "Traffic Separation — minimum distance standard between aircraft",
      "Taxiway Surface — pavement condition report code"]),
    ("TSRA", "wx", "Thunderstorm with rain — a thunderstorm cell accompanied by rainfall",
     ["Terminal Standard Radar Approach procedure",
      "Transponder Signal Range Attenuation factor",
      "Traffic Separation — Radar Advisory service"]),
    ("SHRA", "wx", "Shower rain — intermittent rainfall, not continuous precipitation",
     ["Standard Holding and Route Assignment",
      "Secondary Hazard Reporting Area designation",
      "Squawk Hold — Radar Approach instruction"]),
    ("BR", "wx", "Mist — visibility reduced to between 1,000m and 9,999m by water droplets",
     ["Braking Report — runway friction measurement",
      "Base Report — field elevation and obstacle data",
      "Block Release — ATC pushback approval code"]),
    ("FG", "wx", "Fog — visibility below 1,000m, extremely serious for VFR flight",
     ["Flight Guard — terrain proximity warning active",
      "Fuel Gauge — cockpit quantity indicator reading",
      "Final Gate — last hold-short point before the runway"]),
    ("BKN", "wx", "Broken cloud — covering 5 to 7 oktas (more than half the sky)",
     ["Beacon — ground-based navigation transmitter",
      "Braking action Known — confirmed runway friction",
      "Block Negative — ATC clearance refused"]),
    ("FEW", "wx", "Few cloud — covering only 1 to 2 oktas of the sky",
     ["Final Entry Waypoint on an approach procedure",
      "Fuel Endurance Warning activation threshold",
      "Forward Edge Waypoint — GPS fix at route boundary"]),
    ("SCT", "wx", "Scattered cloud — covering 3 to 4 oktas (less than half the sky)",
     ["Standard Cruise Track — planned route centreline",
      "Secondary Control Transponder unit",
      "Speed Control Threshold — approach deceleration point"]),
    ("OVC", "wx", "Overcast — complete 8-okta cloud cover across the entire sky",
     ["Obstacle Vertical Clearance — minimum terrain separation",
      "On-board Voice Communications system",
      "Outbound Vector Change — ATC radar heading instruction"]),
    ("CB", "wx", "Cumulonimbus — the thunderstorm cloud, always avoid in flight",
     ["Control Boundary — edge of a controlled airspace sector",
      "Compass Bearing — magnetic direction to a fix",
      "Circuit Breaker — electrical protection device in the panel"]),
    ("TCU", "wx", "Towering Cumulus — large developing storm cloud, a precursor to CB",
     ["Terminal Control Unit — ATC radar approach facility",
      "Transponder Code Update — squawk reassignment",
      "Traffic Conflict Uplink — TCAS resolution advisory"]),
    ("PROB", "wx", "Probability — the percentage chance of a weather event occurring in a TAF",
     ["Prohibited — designation for restricted airspace",
      "Planned Route of Business — dispatcher scheduling term",
      "Pressure Reading On Board — cabin altitude reference"]),
    ("TEMPO", "wx", "Temporary — a weather change in a TAF lasting less than one hour at a time",
     ["Temperature Offset — ISA deviation value in degrees",
      "Terminal Point — final fix before the destination",
      "Transponder Emergency Override activation"]),
    ("BECMG", "wx", "Becoming — a gradual permanent weather change occurring over a stated time period",
     ["Below Cloud — meteorological ceiling descriptor",
      "Beacon Course Management Group — navaid admin body",
      "Braking Efficiency Change — runway condition update"]),
    ("FIR", "airspace", "Flight Information Region — a defined block of airspace managed by one ATC authority",
     ["Final Instrument Radial — last bearing before a fix",
      "Fuel Indication Reading — cockpit gauge value",
      "Forward ILS Reference — approach intercept point"]),
    ("VOR", "nav", "VHF Omnidirectional Range — ground-based radio navaid that gives you a bearing to or from it",
     ["Vertical Obstacle Reference — charted high terrain marker",
      "Variable Output Radial — GPS computed track label",
      "Verified Overflight Request — diplomatic clearance document"]),
    ("DCT", "nav", "Direct — fly straight to the next fix with no airway or procedure joining required",
     ["Descent Clearance Time — when ATC clears you to descend",
      "Deferred Crew Transfer — operations scheduling term",
      "Digital Chart Track — GPS moving map display mode"]),
    ("STAR", "nav", "Standard Terminal Arrival Route — a published arrival procedure into an airfield",
     ["Short Term Altitude Restriction — temporary height limit",
      "Squawk Transponder Acknowledgement Report",
      "Secondary Traffic Advisory Radar system"]),
    ("CDI", "nav", "Course Deviation Indicator — the needle showing if you are left or right of your planned track",
     ["Cockpit Display Interface — primary flight screen",
      "Controlled Departure Interval — ATC slot timing",
      "Communication Data Input — radio programming port"]),
    ("TOW", "perf", "Takeoff Weight — the total aircraft weight at the moment of departure",
     ["Top Of Waypoint — where a procedure turn begins",
      "Transponder Output Wattage rating",
      "Traffic Ordering Window — ATC sequence slot"]),
    ("LAW", "perf", "Landing Weight — the estimated aircraft weight on arrival after burning off fuel",
     ["Low Altitude Warning — GPWS activation threshold",
      "Lateral Advisory Window — RNP corridor limit",
      "Local Aerodrome Weather — alternative term for ATIS"]),
    ("ZFW", "perf", "Zero Fuel Weight — aircraft weight with everything loaded except fuel",
     ["Zone Flight Warning — restricted area alert",
      "Zenith Fix Waypoint — highest point on a route",
      "Zone of Fixed Weather — stable air mass descriptor"]),
    ("MTOW", "perf", "Maximum Takeoff Weight — the heaviest the aircraft is certified to depart at (2,150 lbs for the Cherokee)",
     ["Minimum Takeoff Weather — lowest VFR conditions allowed",
      "Max Track Over Water — oceanic route distance limit",
      "Mandatory Transponder Output Wattage requirement"]),
    ("USG", "fuel", "US Gallons — the volume unit for avgas; the Cherokee 140 holds 50 USG total",
     ["Upper Sector Guard — frequency monitoring service",
      "Unserviceable Ground equipment tag",
      "Universal Signal Generator — ILS test equipment"]),
    ("CONT", "fuel", "Contingency fuel — the buffer carried for unexpected routing, weather or wind deviations",
     ["Continuous — TAF descriptor for persistent weather",
      "Contact — ATC instruction to call a new frequency",
      "Controlled — the prefix used for controlled airspace"]),
    ("ALTN", "fuel", "Alternate fuel — the fuel planned to fly to your divert airport if the destination is unusable",
     ["Altitude — generic height reference in a flight plan",
      "Along Track — distance measured on the planned route",
      "Alerting — ATC emergency phase declaration"]),
    ("FINRES", "fuel", "Final Reserve — the minimum fuel that must remain in the tanks at the point of landing",
     ["Final Restriction — last airspace boundary before destination",
      "Finished Route Segment — the last leg of a flight plan",
      "Frequency In Reserve — standby radio channel"]),
    ("BLOCK", "fuel", "Block fuel — total fuel loaded before taxi, covering trip, contingency, alternate and reserve",
     ["Block time — the total door-to-door scheduled flight time",
      "Blocked — ATC term for a stepped-on radio transmission",
      "Block altitude — a range of cruise levels approved by ATC"]),
    ("TOC", "nav", "Top of Climb — the geographic point in the flight where you level off at cruise altitude",
     ["Track Over Course — angular difference from planned route",
      "Time on Course — elapsed flying time since departure fix",
      "Transponder Output Check — pre-flight serviceability test"]),
    ("TOD", "nav", "Top of Descent — the point where you begin descending toward your destination",
     ["Time of Departure — the wheels-off recorded time",
      "Track Omni Deviation — VOR needle deflection reading",
      "Transponder Off Date — maintenance schedule entry"]),
    ("MORA", "nav", "Minimum Off-Route Altitude — the lowest safe altitude in an area, including terrain clearance buffer",
     ["Maximum Operational Radar Altitude for ATC coverage",
      "Mandatory Oceanic Reporting Area boundary",
      "Minimum Obstacle Reception Angle for VOR signal"]),
    ("EFOB", "fuel", "Estimated Fuel On Board — the predicted fuel remaining at each waypoint along the route",
     ["En-route Fix Over a Beacon — position reporting point",
      "Emergency Frequency On Board — 121.5 monitoring note",
      "Extended Final On Base — circuit joining position"]),
    ("TMA", "airspace", "Terminal Manoeuvring Area — the block of controlled airspace surrounding a busy airport",
     ["Transponder Mandatory Altitude — the level requiring Mode C",
      "Track Made good Average — a navigation accuracy measure",
      "Temporary Movement Area — an apron access restriction"]),
    ("ATC", "atc", "Air Traffic Control — the ground-based service that manages the separation of aircraft",
     ["Automatic Track Correction — GPS steering function",
      "Aerodrome Traffic Circuit — the standard joining pattern",
      "Altitude Transition Check — pressurisation step"]),
    ("ATIS", "atc", "Automatic Terminal Information Service — recorded broadcast of weather and runway in use",
     ["Air Traffic Intercept Signal — military scramble term",
      "Airborne Terrain Imaging System",
      "Approach Transition Identification Segment"]),
    ("ICAO", "atc", "International Civil Aviation Organisation — the UN body that sets global aviation standards",
     ["Integrated Civil Airspace Operations body",
      "International Controller and Airman Organisation",
      "Inter-Continental Aviation Oversight authority"]),
    ("NOTAM", "atc", "Notice To Airmen — an official notice of any change or hazard that could affect your flight",
     ["Night Operations Traffic and Movement log",
      "Navigation Options Timing and Altitude Memo",
      "Non-standard Operations Tracking and Monitoring"]),
    ("OBS", "nav", "Omni Bearing Selector — the knob on the GNS 430 or VOR indicator that sets your desired course",
     ["On-Board System — generic avionics reference term",
      "Obstacle — charted high terrain or man-made structure",
      "Outbound Bearing Segment — the departing leg of a hold"]),
    ("UTC", "atc", "Coordinated Universal Time — the single standard time zone used across all of aviation worldwide",
     ["Upper Track Clearance — cruise flight level approval",
      "Uniform Traffic Code — ICAO transponder standard",
      "Ultra-high frequency Transmission Channel"]),
    ("PBN", "nav", "Performance Based Navigation — navigation using certified GPS accuracy and integrity standards",
     ["Pilot Briefing Note — pre-flight information document",
      "Primary Beacon Network — VOR and NDB ground infrastructure",
      "Pressure Based Navigation — altimetry system mode"]),
    ("RVSM", "atc", "Reduced Vertical Separation Minima — permits 1,000ft vertical separation above FL290",
     ["Radar Vector Standard Minimum — ATC lateral spacing rule",
      "Required VHF Squelch Modulation setting",
      "Runway Visual Segment Marker on approach lighting"]),
    ("OAT", "wx", "Outside Air Temperature — the temperature of the air at your current altitude",
     ["On Approach Track — the final inbound course to a runway",
      "Oceanic Area Transition — the entry point to oceanic airspace",
      "Outbound Approach Track — the departing radial from a VOR"]),
    ("ISA", "wx", "International Standard Atmosphere — the standard model used for all aircraft performance calculations",
     ["Instrument Separation Altitude — IFR vertical spacing standard",
      "Integrated Situational Awareness — avionics display mode",
      "In-sector Alert — ATC conflict warning system"]),
    ("ETA", "nav", "Estimated Time of Arrival — your expected time of arrival at the destination",
     ["En-route Track Adjustment — ATC re-route instruction",
      "Emergency Transponder Activation procedure",
      "Elevation Threshold Altitude — approach minimum height"]),
    ("EET", "nav", "Estimated Elapsed Time — time from departure to reach a specific waypoint or destination",
     ["En-route Entry Time — when you enter controlled airspace",
      "Emergency Equipment Test — pre-flight check item",
      "Extended Endurance Time — maximum fuel duration"]),
    ("W/C", "wx", "Wind Component — the headwind or tailwind element that directly affects your ground speed",
     ["Weather Check — the pre-flight briefing stage",
      "Weight and Centre of gravity — loading document",
      "Waypoint Confirmation — GPS fix successfully verified"]),

    # Navigation
    ("SID", "nav", "Standard Instrument Departure — a published departure procedure guiding you clear of the airfield",
     ["Secondary ILS Display — backup approach indicator",
      "System Initialisation Data — FMS startup sequence",
      "Speed Increase Directive — ATC acceleration instruction"]),
    ("NDB", "nav", "Non-Directional Beacon — a ground-based radio transmitter your ADF needle points toward",
     ["Navigation Data Block — waypoint information stored in the FMS",
      "Night Departure Ban — curfew restriction at an airfield",
      "Network Distribution Board — airspace data management system"]),
    ("DME", "nav", "Distance Measuring Equipment — ground transponder that gives you slant-range distance to a station",
     ["Directional Magnetic Error — compass deviation value",
      "Descent Management Entry — FMS altitude planning input",
      "Digital Map Engine — moving map display processor"]),
    ("ILS", "nav", "Instrument Landing System — precision approach aid providing lateral and vertical guidance to the runway",
     ["Integrated Lighting System — runway edge light control unit",
      "In-flight Landing Summary — approach briefing card",
      "Initial Level Step — first cruise altitude assignment"]),
    ("RNAV", "nav", "Area Navigation — allows flight on any desired path using GPS or other sensor inputs",
     ["Radio Navigation Aid Validation — navaid accuracy check",
      "Route Network and Airway — en-route chart reference",
      "Radar Navigation Advisory — ATC vectoring service"]),
    ("FMS", "nav", "Flight Management System — the onboard computer managing routing, performance and fuel planning",
     ["Fuel Monitoring System — tank quantity management unit",
      "Frequency Management Scanner — radio auto-tuning system",
      "Flight Mode Selector — autopilot engagement panel"]),
    ("ETD", "nav", "Estimated Time of Departure — the expected wheels-off time at the departure airfield",
     ["En-route Track Deviation — distance off the planned route",
      "Emergency Traffic Declaration — priority handling request to ATC",
      "Elevation and Terrain Data — obstacle chart information"]),
    ("MSA", "nav", "Minimum Sector Altitude — the lowest safe altitude within a 25nm sector around a navaid",
     ["Maximum Speed Altitude — level above which VMO applies",
      "Multi-Sensor Approach — combined GPS and ILS procedure",
      "Mandatory Stop Airfield — alternate with guaranteed fuel"]),

    # ATC / Comms
    ("SQUAWK", "atc", "The four-digit transponder code assigned by ATC to identify your aircraft on radar",
     ["A verbal readback procedure confirming an ATC clearance",
      "The audio alert generated by a TCAS resolution advisory",
      "An encoded datalink message sent via ACARS"]),
    ("FPL", "atc", "Filed Flight Plan — the formal document submitted to ATC before departure",
     ["Final Position Limit — the last approved waypoint on a route",
      "Frequency Planning List — radio channel allocation sheet",
      "Forward Path Length — total great circle distance of a route"]),
    ("VOLMET", "atc", "Continuous VHF broadcast of METARs and TAFs for key airports, updated hourly",
     ["Volume Metering — ATC flow control technique for sector loading",
      "Volcanic Met — ash cloud advisory issued by a VAAC",
      "VHF Omni Long-range Met — extended range weather relay service"]),
    ("TWR", "atc", "Tower — the ATC unit controlling aircraft on the runway and in the circuit",
     ["Track Width Requirement — RNP corridor specification",
      "Transponder Warning — SSR interrogation failure alert",
      "Turbulence Warning Report — pilot weather advisory message"]),
    ("APP", "atc", "Approach Control — the ATC unit managing arriving and departing traffic in the terminal area",
     ["Autopilot — the aircraft system maintaining course and altitude",
      "Airport — generic reference to the destination aerodrome",
      "Approved — ATC confirmation of a pilot request"]),
    ("ACARS", "atc", "Aircraft Communications Addressing and Reporting System — digital datalink between aircraft and ground",
     ["Automated Chart and Route System — electronic nav chart platform",
      "ATC Clearance and Route Sequencer — slot allocation tool",
      "Airborne Collision Avoidance and Radar System"]),
    ("PIREP", "atc", "Pilot Report — an in-flight weather observation radioed to ATC or a met office",
     ["Primary IFR Route Entry Point — first fix after departure",
      "Planned Instrument Route Entry Procedure",
      "Position Identification and Reporting Protocol"]),

    # Weather
    ("RA", "wx", "Rain — continuous liquid precipitation as reported in a METAR",
     ["Radar Altimeter — the radio altimeter measuring height above ground",
      "Route Advisory — a pilot briefing note for a specific airway",
      "Runway Available — ATC confirmation of runway state"]),
    ("SN", "wx", "Snow — frozen precipitation, significantly reduces visibility and risks icing",
     ["Speed Noise — airframe buffet onset at high indicated airspeed",
      "Standard Notation — ICAO flight plan format reference",
      "Sector Number — ATC radar display identification label"]),
    ("DZ", "wx", "Drizzle — very fine liquid droplets, smaller than rain, reducing visibility",
     ["Danger Zone — prohibited airspace surrounding a hazard area",
      "Descent Zone — airspace block allocated for a descent clearance",
      "DME Zone — area of guaranteed DME signal coverage"]),
    ("RVR", "wx", "Runway Visual Range — the measured distance a pilot can see along the runway, used for low-vis ops",
     ["Radio VHF Range — maximum reception distance of a ground navaid",
      "Route Validation Report — dispatcher pre-flight check document",
      "Radar Vector Route — an ATC-assigned heading sequence"]),
    ("NOSIG", "wx", "No Significant Change — METAR suffix indicating no significant weather change in the next 2 hours",
     ["No Signal — loss of communication with ATC on all frequencies",
      "Non-standard IFR Go-around — missed approach without vertical guidance",
      "Not Significant — flight plan notation for minor route adjustments"]),
    ("SPECI", "wx", "Special Aerodrome Met Report — an unscheduled METAR issued when conditions change rapidly",
     ["Specific — a NOTAM qualifier for a single aircraft type only",
      "Speed Circle — arcs of equal groundspeed on a navigation chart",
      "Special Civilian — an airspace classification for recreational flight"]),
    ("SKC", "wx", "Sky Clear — no cloud of any amount, reported in a METAR when the sky is completely clear",
     ["Squawk Code — the transponder setting assigned by ATC",
      "Sector Keep Clear — a notation for formation flight on charts",
      "Standard Knot Calibration — airspeed system accuracy check"]),
    ("HZ", "wx", "Haze — reduced visibility caused by fine dry particles suspended in the air",
     ["Hertz — the unit of radio frequency measurement",
      "Hazard Zone — charted area of known obstacle or airspace risk",
      "Height Zero — ground level reference datum in obstacle charts"]),

    # Fuel
    ("TRIP", "fuel", "Trip fuel — fuel calculated to fly from takeoff to landing at the destination",
     ["Total Route Inertial Position — FMS computed track label",
      "Transponder Interrogation Pulse — secondary surveillance radar signal",
      "Traffic Report In Progress — ATIS update notification"]),
    ("TAXI", "fuel", "Taxi fuel — the fuel allowance for ground movement before takeoff",
     ["Taxiway — the paved surface used to move between runway and apron",
      "Traffic Avoidance Index — TCAS threat level rating",
      "Transponder Activation — squawk ident instruction from ATC"]),
    ("FOB", "fuel", "Fuel On Board — the total usable fuel currently in the aircraft tanks",
     ["Forward Operating Base — a remote airfield used as a staging point",
      "Frequency Of Broadcast — VOLMET transmission schedule",
      "Flight Operations Bulletin — operator safety notice"]),
    ("EXTRA", "fuel", "Extra fuel — discretionary fuel added by the captain above the calculated minimum",
     ["Extended Range — aircraft certified for long overwater operations",
      "Exterior — the outer surface inspection in a pre-flight walkaround",
      "Exit Track Angle — the radial departing a holding pattern fix"]),

    # Performance
    ("IAS", "perf", "Indicated Airspeed — the speed shown directly on your airspeed indicator, uncorrected for errors",
     ["Initial Approach Segment — the first phase of an instrument approach",
      "Integrated Avionics System — glass cockpit display platform",
      "Instrument Alert Setting — autopilot deviation warning threshold"]),
    ("CAS", "perf", "Calibrated Airspeed — indicated airspeed corrected for instrument and position errors",
     ["Collision Avoidance System — alternative name for TCAS",
      "Controlled Airspace Sector — a defined block of managed airspace",
      "Course Alignment Signal — ILS localiser transmission"]),
    ("MLW", "perf", "Maximum Landing Weight — the heaviest weight at which the aircraft is certified to touch down",
     ["Minimum Level of Weather — lowest conditions acceptable for dispatch",
      "Multi-Link Warning — datalink transmission failure alert",
      "Main Landing Wheel — the primary undercarriage assembly"]),
    ("MZFW", "perf", "Maximum Zero Fuel Weight — the heaviest the aircraft can be with no usable fuel on board",
     ["Minimum Zero-visibility Flight Weather — fog approach limit",
      "Multi-Zone Fuel Warning — low quantity alert across all tanks",
      "Master Zero Fault Warning — all-clear status on system checks"]),
    ("PAX", "perf", "Passengers — the number of occupants used in weight and balance calculations",
     ["Primary Approach fix — the first fix on an instrument approach procedure",
      "Position Accuracy eXponent — GPS integrity measurement value",
      "Precision Approach eXecution — autoland system engagement mode"]),

    # Airspace
    ("CTR", "airspace", "Control Zone — controlled airspace extending from the surface upward around an aerodrome",
     ["Centre — the callsign for an upper area ATC control unit",
      "Clearance To Route — ATC departure routing instruction",
      "Chart Terrain Reference — obstacle elevation datum on a chart"]),
    ("ATZ", "airspace", "Aerodrome Traffic Zone — protected airspace around an airfield, typically 2nm radius to 2,000ft",
     ["Air Traffic Zone — upper airspace division above FL245",
      "Automated Terminal Zone — radar approach control area",
      "Approach Transition Zone — the base segment of a STAR procedure"]),
    ("UIR", "airspace", "Upper Information Region — the airspace above FL245 where upper area control applies",
     ["Uncontrolled IFR Route — a flight path outside controlled airspace",
      "Urgent Incident Report — ATC safety occurrence notification",
      "Ultra-high frequency Interrogation Rate — SSR signal timing"]),
    ("CTA", "airspace", "Control Area — a block of controlled airspace above a specified lower limit",
     ["Crew Training Approval — authority to conduct type rating instruction",
      "Chart Track Annotation — route marking on a navigation chart",
      "Clearance To Approach — ATC instruction to begin descent"]),
]
